name: eje
description: App vom Evangelischen Jugendwerk Esslingen

version: 1.0.4+11

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  add_2_calendar: ^3.0.1
  auto_size_text: ^3.0.0
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.3
  dartz: ^0.10.0
  decorated_icon: ^1.2.1
  envied: ^1.1.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.0
  flutter_background_service_ios: ^5.0.3
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.3
  flutter_local_notifications: ^19.4.2
  flutter_markdown: ^0.7.3
  flutter_native_splash: ^2.4.6
  flutter_native_timezone_latest: ^1.0.0
  flutter_swiper_plus: ^2.0.4
  get_it: ^8.0.3
  get_storage: ^2.0.3
  hive_ce: ^2.11.2
  hive_ce_flutter: ^2.3.1
  html: ^0.15.0
  html2md: ^1.3.1
  http: ^1.2.1
  internet_connection_checker_plus: ^2.8.0
  intl: ^0.20.2
  json_serializable: ^6.6.1
  maps_launcher: ^3.0.0+1
  material_design_icons_flutter: ^7.0.7296
  package_info_plus: ^9.0.0
  page_view_indicators: ^2.0.0
  path_provider: ^2.1.2
  permission_handler: ^12.0.0+1
  persistent_bottom_nav_bar_v2: ^6.0.1
  rxdart: ^0.28.0
  timezone: ^0.10.1
  url_launcher: ^6.2.4
  webfeed_revised: ^0.9.0

dev_dependencies:
  build_runner: ^2.4.15
  # generating secrets
  envied_generator: ^1.1.1
  flutter_test:
    sdk: flutter
    # For Hive to create offline database
  hive_ce_generator: ^1.9.1
  #  linting
  lints: ^6.0.0

# App icon
flutter_launcher_icons:
  image_path: "assets/images/app_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  adaptive_icon_backgorund: "#ffffff"
  adaptive_icon_foreground: "assets/images/app_icon.png"

# Splash screen
flutter_native_splash:
  color: "#000000"
  image: "assets/images/ejelogo.png"

  android_12:
    color: "#000000"
    icon_background_color: "#000000"
    # image: "assets/images/ejelogo_small.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/config/
  fonts:
    - family: CostumIcons
      fonts:
        - asset: assets/fonts/CostumIcons.ttf
