name: eje
description: App vom Evangelischen Jugendwerk Esslingen

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

# For building for android, run "flutter build appbundle --release" in terminal
# to get an Appbundle which includes three apks for each architecture ==> good for uploading to google play store
# "flutter build apk --split-per-abi" can be used to generate three seperate apk
# for each architecture
# "flutter build apk" can be used to build to generate one big fat apk file which works on all architectures

# --obfuscate --split-debug-info=/home/nachtaktiverhalbaffe/dev/eje/logs     obfuscates the apk so its harder to read for humans. Works on all building types

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  material_design_icons_flutter: ^5.0.6996
  json_serializable: ^6.5.4
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.14
  # Offline Database
  hive: ^2.0.4
  # For Storing Settings
  get_storage: ^2.0.3
  # For OS-Specific directories paths
  path_provider: ^2.0.5
  # Service locator
  get_it: ^7.2.0
  # Bloc for state management
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  # Value equality
  equatable: ^2.0.3
  # Functional programming thingies
  dartz: ^0.10.0
  # To deal with internationalized Datetime Formats
  intl: ^0.17.0
  # Remote API
  internet_connection_checker: ^1.0.0+1
  connectivity: ^3.0.6
  http: ^0.13.3
  # Webscraping
  html: ^0.15.0
  # RSS Feed
  # dart_rss: ^2.0.1
  webfeed:
    # FIXME use stable dependecy
    git:
      url: https://github.com/arhamcode/webfeed.git
  # Url opener
  url_launcher: ^6.1.6
  maps_launcher: ^2.0.1
  # to save events to calendar
  add_2_calendar: ^2.2.1
  # Pageviewer Indicator
  page_view_indicators: ^2.0.0
  # Carousel PageView
  flutter_swiper_plus: ^2.0.4
  # Icon Shadows
  decorated_icon: ^1.2.1
  # Bottom Nav bar
  persistent_bottom_nav_bar: ^5.0.2
  # Cached Networkimage
  cached_network_image: ^3.2.2
  # Markdown editor
  flutter_markdown: ^0.6.13
  html2md: ^1.2.6
  # Local Push-Notification
  flutter_local_notifications: ^12.0.3
  # Background services
  workmanager: ^0.5.1
  # For secrets
  envied: ^0.2.3
  flutter_native_timezone: ^2.0.0
  # For managing permissions
  permission_handler: ^10.2.0

# To run build runners und generators, run
# "flutter packages pub run build_runner build --delete-conflicting-outputs" in terminal
dev_dependencies:
  flutter_test:
    sdk: flutter
    # For Hive to create offline database
  hive_generator: ^1.1.3
  # generating secrets
  envied_generator: ^0.2.3
  build_runner: ^2.3.2
  #  linting
  lints: ^2.0.1
  # To get app version as string
  package_info_plus: ^1.0.2

# App icon
# To generate App-Icon run "flutter pub run flutter_launcher_icons:main" in the terminal
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"

# Splash screen
# To generate splash screen run "flutter pub run flutter_native_splash:create" in the terminal
flutter_native_splash:
  color: "#000000"
  image: "assets/images/ejelogo.png"

  android_12:
    color: "#000000"
    image: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/config/
  fonts:
    - family: CostumIcons
      fonts:
        - asset: assets/fonts/CostumIcons.ttf
