name: eje
description: App vom Evangelischen Jugendwerk Esslingen

version: 1.0.1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  add_2_calendar: ^3.0.1
  auto_size_text: ^3.0.0
  bloc: ^8.1.1
  cached_network_image: ^3.3.1
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.3
  dartz: ^0.10.0
  decorated_icon: ^1.2.1
  envied: ^0.5.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_background_service: ^5.0.2
  flutter_background_service_android: ^6.2.2
  flutter_background_service_ios: ^5.0.0
  flutter_bloc: ^8.1.2
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^16.2.0
  flutter_markdown: ^0.6.18+2
  flutter_native_splash: ^2.3.6
  flutter_native_timezone: ^2.0.0
  flutter_swiper_plus: ^2.0.4
  get_it: ^7.2.0
  get_storage: ^2.0.3
  hive: ^2.0.4
  html: ^0.15.0
  html2md: ^1.3.1
  http: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  json_serializable: ^6.6.1
  maps_launcher: ^2.0.1
  material_design_icons_flutter: ^7.0.7296
  package_info_plus: ^4.1.0
  page_view_indicators: ^2.0.0
  path_provider: ^2.0.5
  permission_handler: ^11.1.0
  persistent_bottom_nav_bar_v2: ^4.2.8
  rxdart: ^0.27.7
  timezone: ^0.9.2
  url_launcher: ^6.2.1
  webfeed_revised: ^0.7.1

dev_dependencies:
  build_runner: ^2.3.2
  # generating secrets
  envied_generator: ^0.5.2
  flutter_test:
    sdk: flutter
    # For Hive to create offline database
  hive_generator: ^2.0.0
  #  linting
  lints: ^2.0.1

# App icon
flutter_launcher_icons:
  image_path: "assets/images/app_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  adaptive_icon_backgorund: "#ffffff"
  adaptive_icon_foreground: "assets/images/app_icon.png"

# Splash screen
flutter_native_splash:
  color: "#000000"
  image: "assets/images/ejelogo.png"

  android_12:
    color: "#000000"
    icon_background_color: "#FFFFFF"
    # image: "assets/images/ejelogo_small.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/config/
  fonts:
    - family: CostumIcons
      fonts:
        - asset: assets/fonts/CostumIcons.ttf
