// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:eje/models/article.dart';
import 'package:eje/models/bakler.dart';
import 'package:eje/models/camp.dart';
import 'package:eje/models/employee.dart';
import 'package:eje/models/event.dart';
import 'package:eje/models/field_of_work.dart';
import 'package:eje/models/hyperlink.dart';
import 'package:eje/models/location.dart';
import 'package:eje/models/news.dart';
import 'package:eje/models/offered_service.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ArticleAdapter());
    registerAdapter(BAKlerAdapter());
    registerAdapter(CampAdapter());
    registerAdapter(EmployeeAdapter());
    registerAdapter(EventAdapter());
    registerAdapter(FieldOfWorkAdapter());
    registerAdapter(HyperlinkAdapter());
    registerAdapter(LocationAdapter());
    registerAdapter(NewsAdapter());
    registerAdapter(OfferedServiceAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ArticleAdapter());
    registerAdapter(BAKlerAdapter());
    registerAdapter(CampAdapter());
    registerAdapter(EmployeeAdapter());
    registerAdapter(EventAdapter());
    registerAdapter(FieldOfWorkAdapter());
    registerAdapter(HyperlinkAdapter());
    registerAdapter(LocationAdapter());
    registerAdapter(NewsAdapter());
    registerAdapter(OfferedServiceAdapter());
  }
}
