/// Flutter icons EjeLogo
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EjeLogo
///      fonts:
///       - asset: fonts/EjeLogo.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class EjeLogo {
  EjeLogo._();

  static const _kFontFam = 'EjeLogo';
  static const _kFontPkg = null;

  static const IconData ejeLogo = const IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
