name: Build & Release

on: workflow_dispatch

jobs:
  android-build:
    name: android-release-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate apk token file
        run: |
            touch assets/config/.env
            echo "AMOSURL = ${{secrets.AMOS_URL}}" >> assets/config/.env
            echo "AMOSTOKEN = ${{secrets.AMOS_TOKEN}}" >> assets/config/.env
      - run: |
          echo "${{ secrets.KEYSTORE}}" | base64 -d > android/keystore.jks
          ls -lah android/
        shell: bash
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
            channel: "stable"
      - run: flutter clean
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - env:
          KEY_PWD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_PWD: ${{ secrets.STORE_PASSWORD }}
        run:  flutter build appbundle --release
      - env:
          KEY_PWD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_PWD: ${{ secrets.STORE_PASSWORD }}
        run:  flutter build apk --release
      - name: Upload app bundle
        uses: actions/upload-artifact@v3
        with:
          name: appbundle
          path: build/app/outputs/bundle/release/app-release.aab
      - name: Upload app bundle
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-release.apk

  release:
    name: Create Github release
    needs: [android-build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: appbundle
          path: build
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            pre-release: False
            automatic_release_tag: "latest"
            files: |
              build/app-release.apk
              build/app-release.abb
