name: Build & Release

on: 
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  android-build:
    name: Build signed Android binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate apk token file
        run: |
            touch assets/config/.env
            echo "AMOSURL = ${{secrets.AMOS_URL}}" >> assets/config/.env
            echo "AMOSTOKEN = ${{secrets.AMOS_TOKEN}}" >> assets/config/.env
      - run: |
          echo "${{ secrets.KEYSTORE}}" | base64 -d > android/keystore.jks
        shell: bash
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
            channel: "stable"
      - run: flutter clean
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - env:
          KEY_PWD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_PWD: ${{ secrets.STORE_PASSWORD }}
        run:  flutter build appbundle --release
      - env:
          KEY_PWD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_PWD: ${{ secrets.STORE_PASSWORD }}
        run:  flutter build apk --release
      - name: Upload app bundle
        uses: actions/upload-artifact@v3
        with:
          name: appbundle
          path: build/app/outputs/bundle/release/app-release.aab
          retention-days: 1
      - name: Upload app bundle
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 1
  ios-build:
    name: Build unsigned ios binaries
    runs-on: macos-13
    steps:
      # Checks-out our repository under $GITHUB_WORKSPACE, so our job can access it
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate API token file
        run: |
            touch assets/config/.env
            echo "AMOSURL = ${{secrets.AMOS_URL}}" >> assets/config/.env
            echo "AMOSTOKEN = ${{secrets.AMOS_TOKEN}}" >> assets/config/.env
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_15.0.1.app/Contents/Developer'   
      # Install flutter
      - name: Flutter get
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Install your project's dependencies
      - run: flutter clean
      - run: flutter pub get

      # Build and sign the ipa using a single flutter command
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Building IPA
        run: flutter build ipa --release --no-codesign
          
      # Collect the file and upload as artifact         
      - name: collect ipa artifacts
        uses: actions/upload-artifact@v3
        with:
         name: ipa
         # Path to the release files
         path: build/ios/archive/Runner.xcarchive
 
  release:
    name: Create Github release
    needs: [android-build, ios-build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: appbundle
          path: build
      - uses: actions/download-artifact@v3
        with:
          name: apk
          path: build
      - uses: actions/download-artifact@v3
        with:
          name: ipa
          path: build
      - uses: marvinpinto/action-automatic-releases@latest
        with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            automatic_release_tag: "latest"
            prerelease: false
            title: "Development Build"
            files: |
              build/app-release.apk
              build/app-release.aab
              build/Runner.xcarchive
