name: Android Release build

on: workflow_dispatch

jobs:
  build:
    name: android-release-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate apk token file
        run: |
            touch assets/config/.env
            echo "AMOSURL = ${{secrets.AMOS_URL}}" >> assets/config/.env
            echo "AMOSTOKEN = ${{secrets.AMOS_TOKEN}}" >> assets/config/.env
      - run: echo "${{ secrets.KEYSTORE}}" | base64 -d >> android/keystore.jks
        shell: bash
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
            channel: "stable"
      - run: flutter clean
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - env:
          KEY_PWD: ${{ inputs.key-pwd }}
          KEYSTORE_PWD: ${{ inputs.keystore-pwd }}
        run:  flutter build appbundle --release
      - env:
          KEY_PWD: ${{ inputs.key-pwd }}
          KEYSTORE_PWD: ${{ inputs.keystore-pwd }}
        run:  flutter build apk --release
      - name: Upload app bundle
        uses: actions/upload-artifact@v2
        with:
          name: appbundle
          path: build/app/outputs/bundle/release/app-release.aab
      - name: Upload app bundle
        uses: actions/upload-artifact@v2
        with:
          name: appbundle
          path: build/app/outputs/bundle/release/app-release.apk
